language:
  - node_js

node_js:
  - 12

services:
  - docker

install:
  - echo "nothing to install"

before-script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
  - docker tag udagram-api-feed manlu23/udagram-api-feed
  - docker tag udagram-api-user manlu23/udagram-api-user
  - docker tag udagram-api-frontend manlu23/udagram-api-frontend
  - docker tag udagram-api-reverseproxy manlu23/udagram-api-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manlu23/udagram-api-feed
  - docker push manlu23/udagram-api-user
  - docker push manlu23/udagram-api-frontend
  - docker push manlu23/udagram-api-reverseproxy
